### ISSUE TITLE
Mobile View Not Working Properly

### ISSUE THREAD

**Issue by Mrgig7** [Namratha2604/Darahasa-portfolio#1]
The mobile view of the application is not functioning as expected. Here are some key details and steps to reproduce the issue:

Steps to Reproduce:

Open the application on a mobile device.
Observe that the layout is not displaying correctly.

Expected Behavior:
The mobile view should display all elements correctly and maintain full functionality.

Actual Behavior:
The images and textboxes are getting misaligned, resulting in a distorted layout.

Expected Resolution:
A fix for the mobile view to ensure it displays correctly and functions as intended.
Thank you for your attention to this matter.

**Comment by Namratha2604** [comment]
Hi @Mrgig7
Thank you for bringing this to our attention! We’ve identified the layout issues in the mobile view, especially with the misalignment of images and textboxes.

To address this, we’ve converted the layout to use Bootstrap, which has significantly improved the responsiveness and alignment of all elements across various mobile devices. The mobile view should now display correctly and maintain full functionality as expected.

Please feel free to visit the application and test it out. Let us know if you encounter any further issues!

Thanks again for helping us improve.
